version: '3'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=footbot777Azat
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: .
      dockerfile: footbot-backend
    expose:
      - "5001"
    volumes:
      - ./TG_miniApp_back:/app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql://postgres:footbot777Azat@db/mydb
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: footbot-frontend
    expose:
      - "5173"
    volumes:
      - ./TG_miniApp_front:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://www.findyoursport.ru/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 