"""Add score mismatch fields

Revision ID: 74c447be0771
Revises: 21e7a83741dd
Create Date: 2025-03-09 13:48:43.165444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c447be0771'
down_revision = '21e7a83741dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_submission_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('score_mismatch', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_mismatch_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('score_mismatch_count')

    with op.batch_alter_table('game_rooms', schema=None) as batch_op:
        batch_op.drop_column('score_mismatch')
        batch_op.drop_column('score_submission_attempts')

    # ### end Alembic commands ###
